gem 'middleman', '~>4.1.7'
gem 'middleman-s3_sync', '~>4.0.2'
gem 'middleman-livereload', '~>3.4.6'
gem 'middleman-minify-html', '~>3.4.1'
gem 'middleman-imageoptim', '~>0.2.1'
gem 'therubyracer', '~> 0.12.2'
